import { StyleSheet, Platform } from 'react-native';
import { Colors, Spacing, BorderRadius } from '@/constants/theme';

export const createStyles = (theme: typeof Colors.light) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundRoot,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      backgroundColor: theme.backgroundDefault,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
    },
    dateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.md,
      backgroundColor: theme.backgroundTertiary,
    },
    dateText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    headerButtons: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    iconButton: {
      width: 36,
      height: 36,
      borderRadius: BorderRadius.md,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.backgroundTertiary,
    },
    addButton: {
      backgroundColor: theme.primary,
    },
    taskList: {
      flex: 1,
      paddingHorizontal: Spacing.sm,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingVertical: Spacing['3xl'],
    },
    emptyText: {
      fontSize: 14,
      marginTop: Spacing.xs,
    },
    patientCard: {
      backgroundColor: theme.backgroundDefault,
      marginHorizontal: Spacing.sm,
      marginTop: Spacing.xs,
      borderRadius: BorderRadius.md,
      overflow: 'hidden',
      ...Platform.select({
        android: {
          elevation: 1,
        },
      }),
    },
    patientHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm,
    },
    patientInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    bedBadge: {
      backgroundColor: theme.primary,
      paddingHorizontal: Spacing.xs,
      paddingVertical: 1,
      borderRadius: BorderRadius.sm,
    },
    bedNumber: {
      fontWeight: '600',
      fontSize: 12,
    },
    patientHeaderRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    tasksContainer: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.borderLight,
      padding: Spacing.xs,
    },
    taskItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: Spacing.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
    },
    taskLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      flex: 1,
    },
    taskInfo: {
      gap: 2,
    },
    taskName: {
      fontWeight: '500',
    },
    taskRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    timerDisplay: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      minWidth: 60,
    },
    taskActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    editTaskButton: {
      width: 32,
      height: 32,
      borderRadius: BorderRadius.sm,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.backgroundRoot,
    },
    deleteTaskButton: {
      width: 32,
      height: 32,
      borderRadius: BorderRadius.sm,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
    },
    timerButtons: {
      flexDirection: 'row',
      gap: 4,
    },
    timerButton: {
      width: 32,
      height: 32,
      borderRadius: BorderRadius.md,
      justifyContent: 'center',
      alignItems: 'center',
    },
    startButton: {
      backgroundColor: theme.primary,
    },
    pauseButton: {
      backgroundColor: '#F59E0B',
    },
    completeButton: {
      backgroundColor: theme.success,
    },
    collectButton: {
      backgroundColor: theme.success,
    },
    collectionPrompt: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 2,
      backgroundColor: 'rgba(245, 158, 11, 0.15)',
      borderRadius: BorderRadius.sm,
    },
    collectionText: {
      fontSize: 12,
      fontWeight: '600',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalContainer: {
      backgroundColor: theme.backgroundDefault,
      borderRadius: 16,
      width: '90%',
      maxWidth: 400,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 8,
    },
    modalContent: {
      padding: 12,
      flex: 1,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: Spacing.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
    },
    modalBody: {
      gap: Spacing.lg,
      maxHeight: 400,
    },
    formGroup: {
      gap: Spacing.xs,
    },
    label: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    input: {
      backgroundColor: theme.backgroundRoot,
      borderRadius: BorderRadius.lg,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.md,
      borderWidth: 1,
      borderColor: theme.border,
      minHeight: 48,
      fontSize: 16,
    },
    textInput: {
      color: theme.textPrimary,
    },
    textArea: {
      minHeight: 88,
      paddingTop: Spacing.sm,
      textAlignVertical: 'top',
    },
    projectSelector: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.sm,
    },
    projectOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundRoot,
      borderWidth: 1.5,
      borderColor: theme.border,
    },
    projectOptionSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    modalFooter: {
      flexDirection: 'row',
      gap: Spacing.sm,
      paddingTop: Spacing.sm,
      paddingBottom: Spacing.xs,
    },
    modalButton: {
      flex: 1,
      paddingVertical: Spacing.md,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      minHeight: 48,
    },
    cancelButton: {
      backgroundColor: theme.backgroundRoot,
      borderWidth: 1,
      borderColor: theme.border,
    },
    cancelButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.textSecondary,
    },
    confirmButton: {
      backgroundColor: theme.primary,
    },
    confirmButtonText: {
      fontSize: 16,
      fontWeight: '600',
    },
    // 导入模态框样式
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: theme.backgroundRoot,
      borderRadius: BorderRadius.lg,
      marginBottom: Spacing.md,
    },
    searchInput: {
      flex: 1,
      fontSize: 15,
      color: theme.textPrimary,
      paddingVertical: 0,
    },
    patientList: {
      maxHeight: 300,
    },
    patientSelectItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
    },
    patientSelectLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    bedBadgeSmall: {
      backgroundColor: theme.primary,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 2,
      borderRadius: BorderRadius.sm,
      minWidth: 32,
      alignItems: 'center',
      flexShrink: 0,
    },
    selectedPatientHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: Spacing.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
      marginBottom: Spacing.md,
    },
    backButton: {
      width: 40,
      height: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    selectedPatientInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    sectionLabel: {
      marginBottom: Spacing.md,
      fontWeight: '500',
    },
    projectList: {
      maxHeight: 280,
    },
    importProjectItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
    },
    importProjectItemSelected: {
      backgroundColor: theme.backgroundTertiary,
    },
    importProjectLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    checkbox: {
      width: 22,
      height: 22,
      borderRadius: BorderRadius.sm,
      borderWidth: 2,
      borderColor: theme.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkboxChecked: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    importProjectInfo: {
      gap: 2,
    },
    gotoPatientButton: {
      marginTop: Spacing.md,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.md,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.md,
    },
    // 批量导入样式 - 使用病人列表页相同样式
    importSearchWrapper: {
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      backgroundColor: theme.backgroundDefault,
    },
    importSearchInputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: theme.backgroundRoot,
      borderRadius: BorderRadius.lg,
    },
    importSearchInput: {
      flex: 1,
      fontSize: 15,
      color: theme.textPrimary,
      paddingVertical: 0,
    },
    importPatientList: {
      flex: 1,
    },
    importPatientItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: Spacing.sm,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.borderLight,
    },
    importPatientItemLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      flex: 0.6,
    },
    importPatientName: {
      flexShrink: 1,
    },
    importPatientItemRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      flex: 0.4,
      justifyContent: 'flex-end',
    },
    importProjectsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 4,
      justifyContent: 'flex-end',
      maxWidth: 280,
    },
    importProjectTag: {
      paddingHorizontal: 8,
      paddingVertical: 2,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.sm,
      borderWidth: 1,
      borderColor: theme.border,
    },
    importProjectTagSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    // 历史任务项
    historyTaskItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      padding: Spacing.sm,
      backgroundColor: theme.backgroundRoot,
      borderRadius: BorderRadius.md,
      marginBottom: Spacing.sm,
    },
    historyTaskItemSelected: {
      backgroundColor: theme.backgroundTertiary,
    },
    historyTaskInfo: {
      flex: 1,
      gap: 2,
    },
    // 导入模态框日期选择按钮
    importDateButton: {
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.md,
      borderWidth: 1,
      borderColor: theme.border,
      minWidth: 56,
    },
    importDateButtonActive: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
  });
